name = "kyle-interactions"
account_id = "db47db45acd22a503f31e76887a98caa"
workers_dev = true
kv_namespaces = [
	{ binding = "GRAPH_STORAGE", id = "2063fcb6d8424e5d99c2c922beacf826", preview_id = "2063fcb6d8424e5d99c2c922beacf826" }
]
compatibility_date = "2022-04-11"

[triggers]
crons = ["0 * * * *"]

[miniflare]
watch = true
live_reload = true
env_path = ".env"
cf_fetch = false